name: Sanitizers build
on:
  - push
  - pull_request
permissions:
  contents: read

jobs:
  sanitizers:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq gcc clang meson llvm
          sudo apt-get install -qq libapparmor-dev libcap-dev libseccomp-dev libselinux1-dev linux-libc-dev libpam0g-dev docbook2x

      - name: Compiler version
        env:
          CC: ${{ matrix.compiler }}
        run: |
          ${CC} --version

      - name: Kernel version
        run: |
          uname -a

      - name: Mount table
        run: |
          findmnt

      - name: Build
        run: |
          sudo CC=${{ matrix.compiler }} CXX=${{ matrix.compiler }}++ .github/workflows/sanitizers.sh
